#!/bin/sh

YELP_VERSION=v0.13.1
PRE_COMMIT_CONFIG_FILE=.pre-commit-config.yaml
BASELINE_FILE=.secrets.baseline

set -e

add_pre_commit_config () {

/bin/cat <<EOM >$PRE_COMMIT_CONFIG_FILE
- repo: git@github.com:Yelp/detect-secrets
  rev: $YELP_VERSION
  hooks:
  -   id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: .*/tests/.*
EOM

}

add_baseline_file () {

/bin/cat <<EOM >$BASELINE_FILE
{
  "exclude": {
    "files": null,
    "lines": null
  },
  "generated_at": "2020-05-30T19:28:10Z",
  "plugins_used": [
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "ArtifactoryDetector"
    },
    {
      "base64_limit": 4.5,
      "name": "Base64HighEntropyString"
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "hex_limit": 3,
      "name": "HexHighEntropyString"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "keyword_exclude": null,
      "name": "KeywordDetector"
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "StripeDetector"
    }
  ],
  "results": {},
  "version": "0.13.0",
  "word_list": {
    "file": null,
    "hash": null
  }
}
EOM

}


# Step 1: Check for pip dependency
which pip
if [ $? -ne 0 ]; 
then 
    echo "Please install pip first"
    exit 1 
fi

# Step 2: Install pre-commit
pip install pre-commit

# Step 3: Add pre commit config
add_pre_commit_config

# Step 4: Add baseline file
add_baseline_file

# Step 5: Install the hooks
pre-commit install
